# Generated by Django 2.0.3 on 2022-12-31 22:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0004_auto_20230101_0014'),
        ('register', '0012_userprofile_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company',
            new_name='team',
        ),
    ]
